In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from sklearn.linear_model import LinearRegression as LR
from numpy.polynomial.polynomial import polyfit as pfit
import pandas as pd
import seaborn as sns

In [2]:
location_amount = 10
#location_amount = 6
individual_amount = 10
#individual_amount = 4
time_stamps = 20
#groups = 5
gamma_values = np.linspace(1, 10, 10, endpoint = True)
beta_values = np.linspace(1, 10, 10, endpoint = True)
rho_values = np.linspace(0.1, 1.0, 10, endpoint=True)
#simulation_amount = 10
simulation_amount = 10

In [3]:
#print(pd.options.display.max_rows)
#print(pd.options.display.max_columns)

#michaelis_inputs = np.load(r'C:\Users\tjbro\Desktop\Thesis_Project\Salvaging_Von_Neumann_Entropy\full_input_list_for_location_10_individuals_10_time_20_simulations_10.npy')
VNE_outputs_IxS = np.load(r'C:\Users\tjbro\Desktop\Thesis_Project\Thesis_code\10_by_10_by_20_by_10\numpy_arrays_of_VNE\IxS_iterating_through_all_3_knobs_where_location_10_individual_10_time_20_simulations_10.npy')
VNE_outputs_IxI = np.load(r'C:\Users\tjbro\Desktop\Thesis_Project\Thesis_code\10_by_10_by_20_by_10\numpy_arrays_of_VNE\IxI_iterating_through_all_3_knobs_where_location_10_individual_10_time_20_simulations_10.npy')
VNE_outputs_Tripartite = np.load(r'C:\Users\tjbro\Desktop\Thesis_Project\Thesis_code\10_by_10_by_20_by_10\numpy_arrays_of_VNE\full_tripartite_iterating_through_all_3_knobs_where_location_10_individual_10_time_20_simulations_10.npy')
VNE_outputs_Homerange_IxI = np.load(r'C:\Users\tjbro\Desktop\Thesis_Project\Thesis_code\10_by_10_by_20_by_10\numpy_arrays_of_VNE\homerange_IxI_iterating_through_all_3_knobs_where_location_10_individual_10_time_20_simulations_10.npy')
VNE_outputs_SxS = np.load(r'C:\Users\tjbro\Desktop\Thesis_Project\Thesis_code\10_by_10_by_20_by_10\numpy_arrays_of_VNE\SxS_iterating_through_all_3_knobs_where_location_10_individual_10_time_20_simulations_10.npy')

#inputs = np.load(r'C:\Users\tjbro\Desktop\Thesis_Project\Salvaging_Von_Neumann_Entropy\Michaelis_inputs_location_10_individual_10.npy')
IxS_v_outputs = np.load(r'C:\Users\tjbro\Desktop\Thesis_Project\Thesis_code\10_by_10_by_20_by_10\arrays_needed_for_LWB\IxS_outputs_location_10_individual_10.npy')
IxI_v_outputs = np.load(r'C:\Users\tjbro\Desktop\Thesis_Project\Thesis_code\10_by_10_by_20_by_10\arrays_needed_for_LWB\IxI_outputs_location_10_individual_10.npy')
Tripartite_v_outputs = np.load(r'C:\Users\tjbro\Desktop\Thesis_Project\Thesis_code\10_by_10_by_20_by_10\arrays_needed_for_LWB\Tripartite_outputs_location_10_individual_10.npy')
Homerange_IxI_v_outputs = np.load(r'C:\Users\tjbro\Desktop\Thesis_Project\Thesis_code\10_by_10_by_20_by_10\arrays_needed_for_LWB\homerange_IxI_outputs_location_10_individual_10.npy')
SxS_v_outputs = np.load(r'C:\Users\tjbro\Desktop\Thesis_Project\Thesis_code\10_by_10_by_20_by_10\arrays_needed_for_LWB\SxS_outputs_location_10_individual_10.npy')

In [4]:
# This is computing the Michaelis inputs for each output already calculated
input_list = list(range(1, time_stamps + 1))
#print('this is the input list\n', input_list)
one_vector = np.ones(time_stamps)
michaelis_inputs = np.divide(one_vector, input_list)

#print('these are the michaelis inputs\n', michaelis_inputs)


#print('this is the IxS outputs\n', outputs_IxS)
#beta_IxS_collection = np.load('IxS_beta_collection_50_time_10_simulations.npy')

#print('this is the check the shape\n', outputs_IxS.shape)
#print('this is also to check the shape\n', beta_IxS_collection.shape)

In [5]:
####################################################################################################
# Let's do our best to create a pandas dataframe and try to go from there
####################################################################################################
# The columns for my data fram are gamma, beta, rho, timesteps, and the v vector elements
# associated with each timestep and then the simulation number
# Let's first try getting everything in order of simulations
column_list_VNE = ['gamma', 'beta', 'rho', 'timeStep', 'outputValues']
column_list_v_outputs = ['gamma', 'beta', 'rho', 'michaelisInputs', 'outputValues']
# IxS_df = pd.DataFrame(columns = column_list)
# IxI_df = pd.DataFrame(columns = column_list)
# Homerange_IxI_df = pd.DataFrame(columns = column_list)
# SxS_df = pd.DataFrame(columns = column_list)
# Tripartite_df = pd.DataFrame(columns = column_list)
IxS_list = []
IxI_list = []
Homerange_IxI_list = []
SxS_list = []
Tripartite_list = []

IxS_v_values = []
IxI_v_values = []
Homerange_IxI_v_values = []
SxS_v_values = []
Tripartite_v_values = []

for i in range(simulation_amount):
    for j in range(len(gamma_values)):
        for k in range(len(beta_values)):
            for x in range(len(rho_values)):
                for y in range(time_stamps):
                    IxS_list.append([gamma_values[j], beta_values[k], rho_values[x], (y+1), VNE_outputs_IxS[i][j][k][x][y]])
                    IxI_list.append([gamma_values[j], beta_values[k], rho_values[x], (y+1), VNE_outputs_IxI[i][j][k][x][y]])
                    Homerange_IxI_list.append([gamma_values[j], beta_values[k], rho_values[x], (y+1), VNE_outputs_Homerange_IxI[i][j][k][x][y]])
                    SxS_list.append([gamma_values[j], beta_values[k], rho_values[x], (1+y), VNE_outputs_SxS[i][j][k][x][y]])
                    Tripartite_list.append([gamma_values[j], beta_values[k], rho_values[x], (y+1), VNE_outputs_Tripartite[i][j][k][x][y]])

                    IxS_v_values.append([gamma_values[j], beta_values[k], rho_values[x], 1/(y+1), IxS_v_outputs[i][j][k][x][y]])
                    IxI_v_values.append([gamma_values[j], beta_values[k], rho_values[x], 1/(y+1), IxI_v_outputs[i][j][k][x][y]])
                    Homerange_IxI_v_values.append([gamma_values[j], beta_values[k], rho_values[x], 1/(y+1), Homerange_IxI_v_outputs[i][j][k][x][y]])
                    SxS_v_values.append([gamma_values[j], beta_values[k], rho_values[x], 1/(y+1), SxS_v_outputs[i][j][k][x][y]])
                    Tripartite_v_values.append([gamma_values[j], beta_values[k], rho_values[x], 1/(y+1), Tripartite_v_outputs[i][j][k][x][y]])

IxS_VNE_df = pd.DataFrame(np.vstack(np.array(IxS_list)), columns = column_list_VNE)
IxI_VNE_df = pd.DataFrame(np.vstack(np.array(IxI_list)), columns = column_list_VNE)
Homerange_IxI_VNE_df = pd.DataFrame(np.vstack(np.array(Homerange_IxI_list)), columns = column_list_VNE)
SxS_VNE_df = pd.DataFrame(np.vstack(np.array(SxS_list)), columns = column_list_VNE)
Tripartite_VNE_df = pd.DataFrame(np.vstack(np.array(Tripartite_list)), columns = column_list_VNE)

IxS_v_outputs_df = pd.DataFrame(np.vstack(np.array(IxS_v_values)), columns = column_list_v_outputs)
IxI_v_outputs_df = pd.DataFrame(np.vstack(np.array(IxI_v_values)), columns = column_list_v_outputs)
Homerange_IxI_v_outputs_df = pd.DataFrame(np.vstack(np.array(Homerange_IxI_v_values)), columns = column_list_v_outputs)
SxS_v_outputs_df = pd.DataFrame(np.vstack(np.array(SxS_v_values)), columns = column_list_v_outputs)
Tripartite_v_outputs_df = pd.DataFrame(np.vstack(np.array(Tripartite_v_values)), columns = column_list_v_outputs)

gamma  beta  rho  michaelisInputs  outputValues
0    1.0   1.0  0.1         1.000000      2.004479
1    1.0   1.0  0.1         0.500000      1.547195
2    1.0   1.0  0.1         0.333333      1.394767
3    1.0   1.0  0.1         0.250000      1.318553
4    1.0   1.0  0.1         0.200000      1.272825

In [15]:
#####################################################################################
#
#####################################################################################
IxS_list = []
IxI_list = []
Homerange_IxI_list = []
SxS_list = []
Tripartite_list = []

for i in gamma_values:
    gamma_IxS_df = IxS_v_outputs_df[IxS_v_outputs_df.gamma == i]
    gamma_IxI_df = IxI_v_outputs_df[IxI_v_outputs_df.gamma == i]
    gamma_Homerange_IxI_df = Homerange_IxI_v_outputs_df[Homerange_IxI_v_outputs_df.gamma == i]
    gamma_SxS_df = SxS_v_outputs_df[SxS_v_outputs_df.gamma == i]
    gamma_Tripartite_df = Tripartite_v_outputs_df[Tripartite_v_outputs_df.gamma == i]
    
    for j in beta_values:
        beta_IxS_df = gamma_IxS_df[gamma_IxS_df.beta == j]
        beta_IxI_df = gamma_IxI_df[gamma_IxI_df.beta == j]
        beta_Homerange_IxI_df = gamma_Homerange_IxI_df[gamma_Homerange_IxI_df.beta == j]
        beta_SxS_df = gamma_SxS_df[gamma_SxS_df.beta == j]
        beta_Tripartite_df = gamma_Tripartite_df[gamma_Tripartite_df.beta == j]
        
        for k in rho_values:
            rho_IxS_df = beta_IxS_df[beta_IxS_df.rho == k]
            rho_IxI_df = beta_IxI_df[beta_IxI_df.rho == k]
            rho_Homerange_IxI_df = beta_Homerange_IxI_df[beta_Homerange_IxI_df.rho == k]
            rho_SxS_df = beta_SxS_df[beta_SxS_df.rho == k]
            rho_Tripartite_df = beta_Tripartite_df[beta_Tripartite_df.rho == k]

            all_inputs = np.array(rho_IxS_df.michaelisInputs.values).reshape(-1,1)
            
            IxS_reg = LR().fit(all_inputs, np.array(rho_IxS_df.outputValues.values).reshape(-1,1))
            IxI_reg = LR().fit(all_inputs, np.array(rho_IxI_df.outputValues.values).reshape(-1,1))
            Homerange_IxI_reg = LR().fit(all_inputs, np.array(rho_Homerange_IxI_df.outputValues.values).reshape(-1,1))
            SxS_reg = LR().fit(all_inputs, np.array(rho_SxS_df.outputValues.values).reshape(-1,1))
            Tripartite_reg = LR().fit(all_inputs, np.array(rho_Tripartite_df.outputValues.values).reshape(-1,1))
            
            display(IxS_reg.intercept_, IxS_reg.coef_)
            
            IxS_list.append([i, j, k, IxS_reg.intercept_[0]])
            IxI_list.append([i, j, k, IxI_reg.intercept_[0]])
            Homerange_IxI_list.append([i, j, k, Homerange_IxI_reg.intercept_[0]])
            SxS_list.append([i, j, k, SxS_reg.intercept_[0]])
            Tripartite_list.append([i, j, k, Tripartite_reg.intercept_[0]])
            

            
IxS_Max_VNE_df = pd.DataFrame(np.vstack(np.array(IxS_list)), columns = ['gamma', 'beta', 'rho', 'MaxVNE'])
IxI_Max_VNE_df = pd.DataFrame(np.vstack(np.array(IxI_list)), columns = ['gamma', 'beta', 'rho', 'MaxVNE'])
Homerange_IxI_Max_VNE_df = pd.DataFrame(np.vstack(np.array(Homerange_IxI_list)), columns = ['gamma', 'beta', 'rho', 'MaxVNE'])
Tripartite_Max_VNE_df = pd.DataFrame(np.vstack(np.array(Tripartite_list)), columns = ['gamma', 'beta', 'rho', 'MaxVNE'])
SxS_Max_VNE_df = pd.DataFrame(np.vstack(np.array(SxS_list)), columns = ['gamma', 'beta', 'rho', 'MaxVNE'])
       

array([1.09598166])

array([[0.91966142]])

array([1.10083029])

array([[0.92373001]])

array([1.09966072])

array([[0.92274859]])

array([1.10563829])

array([[0.9277645]])

array([1.10933612])

array([[0.93086742]])

array([1.10526315])

array([[0.92744971]])

array([1.11297949])

array([[0.93392466]])

array([1.12439624])

array([[0.94350469]])

array([1.11187349])

array([[0.93299659]])

array([1.07840532])

array([[0.90491274]])

array([1.14255908])

array([[0.95874552]])

array([1.14016812])

array([[0.95673921]])

array([1.14956072])

array([[0.96462074]])

array([1.15282742])

array([[0.9673619]])

array([1.15205764])

array([[0.96671596]])

array([1.15195942])

array([[0.96663354]])

array([1.15492803])

array([[0.96912456]])

array([1.15011495])

array([[0.96508581]])

array([1.1435171])

array([[0.95954941]])

array([1.10270473])

array([[0.92530289]])

array([1.18138925])

array([[0.99132873]])

array([1.18030193])

array([[0.99041634]])

array([1.19629175])

array([[1.00383374]])

array([1.19274908])

array([[1.00086101]])

array([1.1992241])

array([[1.00629433]])

array([1.19796673])

array([[1.00523925]])

array([1.20534448])

array([[1.01143007]])

array([1.1952052])

array([[1.00292199]])

array([1.18440871])

array([[0.99386243]])

array([1.13612335])

array([[0.95334516]])

array([1.23624455])

array([[1.03735898]])

array([1.23386683])

array([[1.03536379]])

array([1.24312164])

array([[1.04312969]])

array([1.24225614])

array([[1.04240343]])

array([1.2501576])

array([[1.04903371]])

array([1.24476383])

array([[1.04450769]])

array([1.25492836])

array([[1.05303696]])

array([1.23954905])

array([[1.04013185]])

array([1.22305597])

array([[1.02629216]])

array([1.16756054])

array([[0.97972477]])

array([1.27961532])

array([[1.07375231]])

array([1.28573491])

array([[1.07888739]])

array([1.29970297])

array([[1.09060828]])

array([1.28555929])

array([[1.07874002]])

array([1.28782893])

array([[1.08064453]])

array([1.30014042])

array([[1.09097536]])

array([1.29191874])

array([[1.08407637]])

array([1.28818704])

array([[1.08094502]])

array([1.27499388])

array([[1.06987437]])

array([1.19523035])

array([[1.0029431]])

array([1.3101915])

array([[1.09940943]])

array([1.3218756])

array([[1.10921381]])

array([1.31792839])

array([[1.10590162]])

array([1.32235466])

array([[1.10961579]])

array([1.33996785])

array([[1.1243954]])

array([1.3220737])

array([[1.10938004]])

array([1.32909982])

array([[1.1152758]])

array([1.32110781])

array([[1.10856954]])

array([1.30467036])

array([[1.09477653]])

array([1.23664423])

array([[1.03769436]])

array([1.33125949])

array([[1.11708803]])

array([1.34287752])

array([[1.12683696]])

array([1.34363356])

array([[1.12747137]])

array([1.33941547])

array([[1.12393188]])

array([1.35644263])

array([[1.13821973]])

array([1.34052592])

array([[1.12486368]])

array([1.35193371])

array([[1.1344362]])

array([1.34696502])

array([[1.13026687]])

array([1.32785742])

array([[1.11423328]])

array([1.23767414])

array([[1.03855857]])

array([1.36490356])

array([[1.14531948]])

array([1.37221654])

array([[1.15145596]])

array([1.37743321])

array([[1.15583338]])

array([1.38945209])

array([[1.16591867]])

array([1.39647902])

array([[1.17181511]])

array([1.39643402])

array([[1.17177736]])

array([1.3590777])

array([[1.14043088]])

array([1.37175888])

array([[1.15107192]])

array([1.34432463])

array([[1.12805126]])

array([1.25274891])

array([[1.05120814]])

array([1.40357857])

array([[1.1777725]])

array([1.40942865])

array([[1.18268143]])

array([1.40884413])

array([[1.18219094]])

array([1.41750042])

array([[1.18945461]])

array([1.4179769])

array([[1.18985444]])

array([1.41375937])

array([[1.18631542]])

array([1.39406321])

array([[1.16978796]])

array([1.40066156])

array([[1.17532477]])

array([1.37523676])

array([[1.15399028]])

array([1.28508742])

array([[1.07834407]])

array([1.44537753])

array([[1.21284689]])

array([1.45023809])

array([[1.21692549]])

array([1.4807376])

array([[1.24251827]])

array([1.4799814])

array([[1.24188373]])

array([1.48018983])

array([[1.24205863]])

array([1.47225096])

array([[1.23539696]])

array([1.46671876])

array([[1.23075477]])

array([1.47541863])

array([[1.23805501]])

array([1.4498106])

array([[1.21656677]])

array([1.24722548])

array([[0.96266119]])

array([1.11854587])

array([[0.93859552]])

array([1.11391962])

array([[0.93471354]])

array([1.11964793])

array([[0.93952029]])

array([1.12126316])

array([[0.94087566]])

array([1.12196436])

array([[0.94146405]])

array([1.12484543])

array([[0.94388162]])

array([1.13276844])

array([[0.95052998]])

array([1.13686137])

array([[0.95396444]])

array([1.12667355])

array([[0.94541563]])

array([1.08712051])

array([[0.91222584]])

array([1.14941694])

array([[0.96450009]])

array([1.1545148])

array([[0.96877782]])

array([1.14765711])

array([[0.96302338]])

array([1.15761831])

array([[0.97138204]])

array([1.16112865])

array([[0.97432764]])

array([1.16457945])

array([[0.97722328]])

array([1.16359656])

array([[0.97639851]])

array([1.16900437])

array([[0.98093632]])

array([1.16584735])

array([[0.9782872]])

array([1.12709707])

array([[0.94577102]])

array([1.21043364])

array([[1.0157005]])

array([1.21136313])

array([[1.01648045]])

array([1.20920872])

array([[1.01467264]])

array([1.21774766])

array([[1.02183785]])

array([1.22695154])

array([[1.02956102]])

array([1.22689745])

array([[1.02951563]])

array([1.22449554])

array([[1.02750014]])

array([1.2059522])

array([[1.01194002]])

array([1.20623411])

array([[1.01217659]])

array([1.15406033])

array([[0.96839646]])

array([1.245698])

array([[1.04529157]])

array([1.24049306])

array([[1.040924]])

array([1.2455341])

array([[1.04515404]])

array([1.2554078])

array([[1.05343927]])

array([1.24182805])

array([[1.04204422]])

array([1.24523189])

array([[1.04490044]])

array([1.25018797])

array([[1.0490592]])

array([1.24471121])

array([[1.04446354]])

array([1.23629401])

array([[1.03740048]])

array([1.17984024])

array([[0.99002892]])

array([1.29721922])

array([[1.08852412]])

array([1.30895004])

array([[1.09836769]])

array([1.30650399])

array([[1.09631516]])

array([1.30924932])

array([[1.09861883]])

array([1.30943045])

array([[1.09877082]])

array([1.30924316])

array([[1.09861366]])

array([1.31119886])

array([[1.10025473]])

array([1.305098])

array([[1.09513537]])

array([1.28282202])

array([[1.07644312]])

array([1.22130591])

array([[1.02482365]])

array([1.27161671])

array([[1.0670405]])

array([1.28774197])

array([[1.08057156]])

array([1.28939396])

array([[1.08195778]])

array([1.28731378])

array([[1.08021225]])

array([1.27902049])

array([[1.07325317]])

array([1.28208877])

array([[1.07582784]])

array([1.28523898])

array([[1.07847125]])

array([1.28597959])

array([[1.0790927]])

array([1.26489907])

array([[1.06140359]])

array([1.21908092])

array([[1.02295661]])

array([1.39539072])

array([[1.1709019]])

array([1.38352515])

array([[1.16094524]])

array([1.38624508])

array([[1.1632276]])

array([1.3960646])

array([[1.17146736]])

array([1.39970351])

array([[1.17452085]])

array([1.39523306])

array([[1.1707696]])

array([1.39059374])

array([[1.16687665]])

array([1.3776932])

array([[1.15605154]])

array([1.36302943])

array([[1.14374686]])

array([1.25238152])

array([[1.05089985]])

array([1.3531663])

array([[1.1354705]])

array([1.35611867])

array([[1.13794789]])

array([1.3602415])

array([[1.14140744]])

array([1.36033008])

array([[1.14148178]])

array([1.3624501])

array([[1.14326073]])

array([1.35229483])

array([[1.13473922]])

array([1.36047667])

array([[1.14160478]])

array([1.3462279])

array([[1.12964834]])

array([1.33127309])

array([[1.11709944]])

array([1.24502634])

array([[1.04472796]])

array([1.37924783])

array([[1.15735606]])

array([1.3876836])

array([[1.16443469]])

array([1.40094465])

array([[1.17556232]])

array([1.41635379])

array([[1.18849245]])

array([1.4069725])

array([[1.18062042]])

array([1.39742277])

array([[1.17260704]])

array([1.39661576])

array([[1.17192986]])

array([1.39709615])

array([[1.17233297]])

array([1.37257033])

array([[1.15175283]])

array([1.25523913])

array([[1.05329773]])

array([1.45077129])

array([[1.21737291]])

array([1.45979702])

array([[1.22494659]])

array([1.47083941])

array([[1.23421249]])

array([1.48223238])

array([[1.24377257]])

array([1.46779021])

array([[1.23165384]])

array([1.45983571])

array([[1.22497905]])

array([1.46550703])

array([[1.22973798]])

array([1.4580376])

array([[1.22347023]])

array([1.45058395])

array([[1.21721571]])

array([1.30966925])

array([[1.0989712]])

array([1.09817951])

array([[0.92150568]])

array([1.10749956])

array([[0.92932633]])

array([1.10110861])

array([[0.92396355]])

array([1.10770621])

array([[0.92949974]])

array([1.109884])

array([[0.93132716]])

array([1.11917696])

array([[0.93912508]])

array([1.11709016])

array([[0.93737401]])

array([1.11720049])

array([[0.93746659]])

array([1.12852051])

array([[0.94696546]])

array([1.09223777])

array([[0.91651984]])

array([1.14436663])

array([[0.96026227]])

array([1.15421253])

array([[0.96852417]])

array([1.15382585])

array([[0.9681997]])

array([1.14439893])

array([[0.96028938]])

array([1.14793414])

array([[0.96325585]])

array([1.16214313])

array([[0.97517891]])

array([1.16178825])

array([[0.97488112]])

array([1.16085335])

array([[0.97409663]])

array([1.16209751])

array([[0.97514063]])

array([1.12897977])

array([[0.94735083]])

array([1.1800988])

array([[0.99024589]])

array([1.19154444])

array([[0.99985017]])

array([1.19190505])

array([[1.00015277]])

array([1.20148121])

array([[1.00818833]])

array([1.20844765])

array([[1.01403401]])

array([1.2041122])

array([[1.01039604]])

array([1.21487831])

array([[1.01943011]])

array([1.2133273])

array([[1.01812863]])

array([1.19990501])

array([[1.0068657]])

array([1.15686905])

array([[0.97075332]])

array([1.2407307])

array([[1.0411234]])

array([1.23805896])

array([[1.03888149]])

array([1.24018354])

array([[1.04066427]])

array([1.23965623])

array([[1.04022179]])

array([1.24506342])

array([[1.04475908]])

array([1.2477518])

array([[1.04701496]])

array([1.25325638])

array([[1.05163397]])

array([1.24170462])

array([[1.04194064]])

array([1.23392163])

array([[1.03540977]])

array([1.18583297])

array([[0.99505756]])

array([1.26202052])

array([[1.05898814]])

array([1.26710706])

array([[1.06325636]])

array([1.26396605])

array([[1.06062068]])

array([1.27128949])

array([[1.06676593]])

array([1.28069465])

array([[1.074658]])

array([1.28196431])

array([[1.0757234]])

array([1.27670688])

array([[1.07131178]])

array([1.27095888])

array([[1.06648851]])

array([1.25959727])

array([[1.05695474]])

array([1.19831252])

array([[1.00552941]])

array([1.30798489])

array([[1.09755782]])

array([1.31355918])

array([[1.10223532]])

array([1.31755569])

array([[1.10558888]])

array([1.32911572])

array([[1.11528915]])

array([1.32736219])

array([[1.11381772]])

array([1.31237488])

array([[1.10124155]])

array([1.33637861])

array([[1.12138359]])

array([1.32761511])

array([[1.11402995]])

array([1.30167097])

array([[1.09225968]])

array([1.24700462])

array([[1.04638798]])

array([1.3393601])

array([[1.12388542]])

array([1.34815316])

array([[1.13126386]])

array([1.3493711])

array([[1.13228586]])

array([1.35211147])

array([[1.13458537]])

array([1.35279925])

array([[1.1351625]])

array([1.36375023])

array([[1.14435169]])

array([1.34168167])

array([[1.1258335]])

array([1.3569232])

array([[1.13862299]])

array([1.3221386])

array([[1.10943449]])

array([1.258591])

array([[1.05611036]])

array([1.36422714])

array([[1.14475188]])

array([1.37545025])

array([[1.15416943]])

array([1.38389209])

array([[1.16125316]])

array([1.4046774])

array([[1.17869455]])

array([1.40027854])

array([[1.17500337]])

array([1.41496784])

array([[1.18732947]])

array([1.41789787])

array([[1.18978812]])

array([1.38484062])

array([[1.16204909]])

array([1.3648262])

array([[1.14525456]])

array([1.29425532])

array([[1.08603704]])

array([1.36674403])

array([[1.14686386]])

array([1.37967208])

array([[1.15771206]])

array([1.37562387])

array([[1.15431511]])

array([1.39742371])

array([[1.17260782]])

array([1.41410718])

array([[1.18660728]])

array([1.39744007])

array([[1.17262155]])

array([1.3996648])

array([[1.17448837]])

array([1.39073944])

array([[1.16699891]])

array([1.37218496])

array([[1.15142946]])

array([1.27914347])

array([[1.07335637]])

array([1.42264108])

array([[1.19376825]])

array([1.44469422])

array([[1.21227351]])

array([1.45269576])

array([[1.21898777]])

array([1.47074227])

array([[1.23413098]])

array([1.46917827])

array([[1.2328186]])

array([1.4610262])

array([[1.22597802]])

array([1.45789409])

array([[1.2233498]])

array([1.4523366])

array([[1.21868639]])

array([1.4116846])

array([[1.18457444]])

array([1.33017716])

array([[1.11617982]])

array([1.08659762])

array([[0.91178707]])

array([1.08861105])

array([[0.91347659]])

array([1.09463159])

array([[0.91852855]])

array([1.10172864])

array([[0.92448383]])

array([1.0940548])

array([[0.91804455]])

array([1.10273207])

array([[0.92532583]])

array([1.10695841])

array([[0.92887224]])

array([1.11409472])

array([[0.93486047]])

array([1.11325273])

array([[0.93415394]])

array([1.07572782])

array([[0.902666]])

array([1.15827331])

array([[0.97193166]])

array([1.15606712])

array([[0.9700804]])

array([1.15936894])

array([[0.97285102]])

array([1.15833335])

array([[0.97198204]])

array([1.16291552])

array([[0.97582704]])

array([1.16599866])

array([[0.97841416]])

array([1.17316982])

array([[0.98443164]])

array([1.17553779])

array([[0.98641865]])

array([1.17121002])

array([[0.98278712]])

array([1.15510339])

array([[0.96927171]])

array([1.20914115])

array([[1.01461594]])

array([1.2125803])

array([[1.01750181]])

array([1.22333739])

array([[1.02652831]])

array([1.23216315])

array([[1.03393419]])

array([1.22346479])

array([[1.02663521]])

array([1.2258326])

array([[1.02862209]])

array([1.23869566])

array([[1.03941576]])

array([1.23023341])

array([[1.0323149]])

array([1.22598999])

array([[1.02875416]])

array([1.1734135])

array([[0.98463612]])

array([1.2348356])

array([[1.0361767]])

array([1.23788719])

array([[1.03873735]])

array([1.25091631])

array([[1.04967037]])

array([1.26010258])

array([[1.05737876]])

array([1.27025612])

array([[1.06589881]])

array([1.26707332])

array([[1.06322806]])

array([1.2809727])

array([[1.07489132]])

array([1.25909231])

array([[1.05653102]])

array([1.25864417])

array([[1.05615497]])

array([1.19789686])

array([[1.00518062]])

array([1.26286889])

array([[1.05970002]])

array([1.26888006])

array([[1.06474413]])

array([1.28253895])

array([[1.07620559]])

array([1.27787218])

array([[1.07228961]])

array([1.28046951])

array([[1.07446908]])

array([1.28340077])

array([[1.07692876]])

array([1.28797755])

array([[1.08076924]])

array([1.2728136])

array([[1.06804484]])

array([1.27303059])

array([[1.06822693]])

array([1.23736932])

array([[1.0383028]])

array([1.29470509])

array([[1.08641445]])

array([1.31351441])

array([[1.10219775]])

array([1.3167135])

array([[1.10488218]])

array([1.32212604])

array([[1.10942396]])

array([1.32084988])

array([[1.10835311]])

array([1.32654707])

array([[1.11313374]])

array([1.32558927])

array([[1.11233002]])

array([1.32297068])

array([[1.11013271]])

array([1.29532238])

array([[1.08693244]])

array([1.24294625])

array([[1.04298252]])

array([1.35478528])

array([[1.13682902]])

array([1.38612471])

array([[1.1631266]])

array([1.38207249])

array([[1.15972629]])

array([1.37768866])

array([[1.15604773]])

array([1.41398534])

array([[1.18650504]])

array([1.38661028])

array([[1.16353405]])

array([1.38012993])

array([[1.15809625]])

array([1.37501184])

array([[1.15380155]])

array([1.35169392])

array([[1.13423499]])

array([1.27560423])

array([[1.07038652]])

array([1.39164342])

array([[1.16775746]])

array([1.39039766])

array([[1.16671212]])

array([1.41194703])

array([[1.18479465]])

array([1.39978703])

array([[1.17459094]])

array([1.42254586])

array([[1.19368836]])

array([1.4153291])

array([[1.18763262]])

array([1.41397633])

array([[1.18649748]])

array([1.41026197])

array([[1.18338068]])

array([1.38369556])

array([[1.16108824]])

array([1.30275799])

array([[1.09317182]])

array([1.41988557])

array([[1.19145605]])

array([1.42487692])

array([[1.1956444]])

array([1.42804428])

array([[1.19830219]])

array([1.42660942])

array([[1.19709817]])

array([1.44265479])

array([[1.21056218]])

array([1.43403855])

array([[1.20333212]])

array([1.43012877])

array([[1.20005133]])

array([1.42757656])

array([[1.19790972]])

array([1.38419676])

array([[1.16150881]])

array([1.3263511])

array([[1.11296929]])

array([1.42857792])

array([[1.19874998]])

array([1.45320535])

array([[1.21941538]])

array([1.47155871])

array([[1.23481607]])

array([1.47152841])

array([[1.23479065]])

array([1.49076757])

array([[1.25093464]])

array([1.48384961])

array([[1.24512963]])

array([1.49375916])

array([[1.25344494]])

array([1.46576833])

array([[1.22995724]])

array([1.4366093])

array([[1.20548928]])

array([1.28653995])

array([[0.99565079]])

array([1.08782613])

array([[0.91281794]])

array([1.0832301])

array([[0.90896131]])

array([1.08724873])

array([[0.91233343]])

array([1.09085628])

array([[0.91536061]])

array([1.09309897])

array([[0.91724249]])

array([1.10326479])

array([[0.92577285]])

array([1.0981754])

array([[0.92150223]])

array([1.10248488])

array([[0.92511841]])

array([1.11084898])

array([[0.9321369]])

array([1.09226295])

array([[0.91654097]])

array([1.15457084])

array([[0.96882484]])

array([1.1760477])

array([[0.98684652]])

array([1.17535292])

array([[0.98626352]])

array([1.17671981])

array([[0.98741051]])

array([1.18424274])

array([[0.99372316]])

array([1.18319699])

array([[0.99284565]])

array([1.18923804])

array([[0.99791482]])

array([1.19180245])

array([[1.00006667]])

array([1.19437995])

array([[1.00222951]])

array([1.13915877])

array([[0.95589224]])

array([1.19383372])

array([[1.00177116]])

array([1.1961527])

array([[1.00371706]])

array([1.20519884])

array([[1.01130786]])

array([1.20032988])

array([[1.00722222]])

array([1.21613505])

array([[1.02048467]])

array([1.21593062])

array([[1.02031313]])

array([1.21787532])

array([[1.02194497]])

array([1.21819568])

array([[1.02221379]])

array([1.22130778])

array([[1.02482522]])

array([1.17879007])

array([[0.98914771]])

array([1.2327864])

array([[1.03445717]])

array([1.22611049])

array([[1.02885527]])

array([1.22688375])

array([[1.02950414]])

array([1.24768949])

array([[1.04696267]])

array([1.24405677])

array([[1.04391438]])

array([1.25162408])

array([[1.05026427]])

array([1.25523217])

array([[1.05329189]])

array([1.25216009])

array([[1.05071404]])

array([1.25156972])

array([[1.05021866]])

array([1.19879071])

array([[1.00593067]])

array([1.2823113])

array([[1.07601456]])

array([1.28453025])

array([[1.07787653]])

array([1.28756967])

array([[1.08042697]])

array([1.29621108])

array([[1.08767816]])

array([1.29853336])

array([[1.08962684]])

array([1.29860834])

array([[1.08968975]])

array([1.29672152])

array([[1.08810649]])

array([1.30329868])

array([[1.09362552]])

array([1.29392861])

array([[1.0857629]])

array([1.23833825])

array([[1.03911585]])

array([1.29176589])

array([[1.08394811]])

array([1.29575222])

array([[1.08729312]])

array([1.3099492])

array([[1.09920611]])

array([1.31070145])

array([[1.09983734]])

array([1.3143273])

array([[1.10287987]])

array([1.31518899])

array([[1.10360293]])

array([1.3238003])

array([[1.11082886]])

array([1.31912284])

array([[1.1069039]])

array([1.30685568])

array([[1.09661027]])

array([1.28174859])

array([[1.07554239]])

array([1.34014384])

array([[1.12454308]])

array([1.3459915])

array([[1.12944997]])

array([1.3571737])

array([[1.13883319]])

array([1.36528313])

array([[1.14563798]])

array([1.36462699])

array([[1.1450874]])

array([1.37454507])

array([[1.15340988]])

array([1.37292759])

array([[1.15205261]])

array([1.3728463])

array([[1.1519844]])

array([1.35724746])

array([[1.13889508]])

array([1.28385481])

array([[1.07730976]])

array([1.39498859])

array([[1.17056446]])

array([1.43063662])

array([[1.20047748]])

array([1.44119649])

array([[1.20933849]])

array([1.44396269])

array([[1.21165966]])

array([1.47508343])

array([[1.23777374]])

array([1.47963107])

array([[1.24158976]])

array([1.46542218])

array([[1.22966678]])

array([1.45816514])

array([[1.22357724]])

array([1.40589543])

array([[1.17971662]])

array([1.31924771])

array([[1.10700869]])

array([1.3549023])

array([[1.13692721]])

array([1.36362269])

array([[1.14424467]])

array([1.37410949])

array([[1.15304437]])

array([1.38244105])

array([[1.16003556]])

array([1.396401])

array([[1.17174965]])

array([1.40990807])

array([[1.18308371]])

array([1.40092515])

array([[1.17554596]])

array([1.38755114])

array([[1.16432354]])

array([1.37123226])

array([[1.15063003]])

array([1.3099889])

array([[1.09923943]])

array([1.43075145])

array([[1.20057384]])

array([1.43788243])

array([[1.20655759]])

array([1.45708788])

array([[1.2226733]])

array([1.46167864])

array([[1.2265255]])

array([1.47040733])

array([[1.23384993]])

array([1.47270506])

array([[1.235778]])

array([1.46487593])

array([[1.22920841]])

array([1.46098147])

array([[1.22594049]])

array([1.44440054])

array([[1.21202708]])

array([1.36035318])

array([[1.14150116]])

array([1.10054063])

array([[0.92348695]])

array([1.11032485])

array([[0.9316971]])

array([1.10930695])

array([[0.93084295]])

array([1.12081506])

array([[0.94049965]])

array([1.11936552])

array([[0.93928331]])

array([1.1215995])

array([[0.94115789]])

array([1.13332976])

array([[0.951001]])

array([1.1362562])

array([[0.95345663]])

array([1.12899012])

array([[0.94735952]])

array([1.11516814])

array([[0.9357612]])

array([1.14511271])

array([[0.96088833]])

array([1.14788041])

array([[0.96321076]])

array([1.15633956])

array([[0.97030901]])

array([1.15539202])

array([[0.9695139]])

array([1.15688674])

array([[0.97076816]])

array([1.16917823])

array([[0.98108221]])

array([1.17146041])

array([[0.98299724]])

array([1.17808999])

array([[0.98856026]])

array([1.1785018])

array([[0.98890582]])

array([1.1444939])

array([[0.96036907]])

KeyboardInterrupt: 

In [11]:
IxS_Max_VNE_df.shape

(1000, 4)

In [7]:
     
#####################################################################################
#
#####################################################################################
SMALL_SIZE = 8
MEDIUM_SIZE = 16
BIGGER_SIZE = 24


plt.rc('font', size=BIGGER_SIZE)          # controls default text sizes
plt.rc('axes', titlesize=BIGGER_SIZE)     # fontsize of the axes title
plt.rc('axes', labelsize=MEDIUM_SIZE)    # fontsize of the x and y labels
plt.rc('xtick', labelsize=MEDIUM_SIZE)    # fontsize of the tick labels
plt.rc('ytick', labelsize=BIGGER_SIZE)    # fontsize of the tired_patchs
plt.rc('legend', fontsize=BIGGER_SIZE)    # legend fontsize
plt.rc('figure', titlesize=SMALL_SIZE)  # fontsize of the figure title

colors = ['r', 'g', 'k', 'b', 'y']

red_patch = mpatches.Patch(color='r', label='IxS')
green_patch = mpatches.Patch(color = 'g', label = 'IxI')
black_patch = mpatches.Patch(color='k', label='Tripartite')
blue_patch = mpatches.Patch(color='b', label='Homerange IxI')
yellow_patch = mpatches.Patch(color='y', label='SxS')

In [8]:
#####################################################################################
# This is getting the VNE for the base value parameters
#####################################################################################
IxS_VNE_graphing_df = IxS_VNE_df[IxS_VNE_df.gamma == 1]
IxS_VNE_graphing_df = IxS_VNE_graphing_df[IxS_VNE_graphing_df.beta == 1]
IxS_VNE_graphing_df = IxS_VNE_graphing_df[IxS_VNE_graphing_df.rho == 0.1]

IxI_VNE_graphing_df = IxI_VNE_df[IxI_VNE_df.gamma == 1]
IxI_VNE_graphing_df = IxI_VNE_graphing_df[IxI_VNE_graphing_df.beta == 1]
IxI_VNE_graphing_df = IxI_VNE_graphing_df[IxI_VNE_graphing_df.rho == 0.1]

Homerange_IxI_VNE_graphing_df = Homerange_IxI_VNE_df[Homerange_IxI_VNE_df.gamma == 1]
Homerange_IxI_VNE_graphing_df = Homerange_IxI_VNE_graphing_df[Homerange_IxI_VNE_graphing_df.beta == 1]
Homerange_IxI_VNE_graphing_df = Homerange_IxI_VNE_graphing_df[Homerange_IxI_VNE_graphing_df.rho == 0.1]

Tripartite_VNE_graphing_df = Tripartite_VNE_df[Tripartite_VNE_df.gamma == 1]
Tripartite_VNE_graphing_df = Tripartite_VNE_graphing_df[Tripartite_VNE_graphing_df.beta == 1]
Tripartite_VNE_graphing_df = Tripartite_VNE_graphing_df[Tripartite_VNE_graphing_df.rho == 0.1]

SxS_VNE_graphing_df = SxS_VNE_df[SxS_VNE_df.gamma == 1]
SxS_VNE_graphing_df = SxS_VNE_graphing_df[SxS_VNE_graphing_df.beta == 1]
SxS_VNE_graphing_df = SxS_VNE_graphing_df[SxS_VNE_graphing_df.rho == 0.1]

In [9]:
#####################################################################################
# Trying to get the avg value for each time value
#####################################################################################
IxS_avg = []
IxI_avg = []
Homerange_IxI_avg = []
Tripartite_avg = []
SxS_avg = []

IxS_VNE_graphing_df[IxS_VNE_graphing_df.timeStep == 1]
# for i in range(time_stamps):
#     IxS_time_step_df = IxS_VNE_graphing_df[IxS_VNE_graphing_df.timeStep == i]
#     IxI_time_step_df = IxI_VNE_graphing_df[IxI_VNE_graphing_df.timeStep == i]
#     Homerange_IxI_time_step_df = Homerange_IxI_VNE_graphing_df[Homerange_IxI_VNE_graphing_df.timeStep == i]
#     Tripartite_time_step_df = Tripartite_VNE_graphing_df[Tripartite_VNE_graphing_df.timeStep == i]
#     SxS_time_step_df = SxS_VNE_graphing_df[SxS_VNE_graphing_df.timeStep == i]
    
    
#     IxS_avg.append(np.sum(IxS_time_step_df.outputValues.values)/10)
#     IxI_avg.append(np.sum(IxI_time_step_df.outputValues.values)/10)
#     Homerange_IxI_avg.append(np.sum(Homerange_IxI_time_step_df.outputValues.values)/10)
#     Tripartite_avg.append(np.sum(Tripartite_time_step_df.outputValues.values)/10)
#     SxS_avg.append(np.sum(SxS_time_step_df.outputValues.values)/10)

# print(IxS_avg, '\n', IxI_avg, '\n', Homerange_IxI_avg, '\n', Tripartite_avg, '\n', 
#       SxS_avg)

this is the length of the avg array
 (20,)
[0.0, 0.7110527188945418, 0.8264862016382171, 0.8560536502997257, 0.8615792624521103, 0.8657698175992019, 0.8743954502533441, 0.8808390020041388, 0.8880629083678032, 0.8888732254186129, 0.8913421578249284, 0.8932825214711257, 0.896162608777004, 0.8976043545749383, 0.8979126857817349, 0.9003759655374161, 0.9003231912149964, 0.9017352692098617, 0.9022117876809308, 0.9026446106260506] 
 [0.0, 0.9077947669221139, 0.9505620399782634, 0.9605369491958745, 0.9662013205868156, 0.9696978647645592, 0.9737707879999331, 0.9753832189514972, 0.9777816685606668, 0.9783299250173659, 0.9797489223599223, 0.980722441760704, 0.9811381770454537, 0.9819007450769297, 0.9821503338272709, 0.982507775250523, 0.9829368982852957, 0.9835390877313428, 0.9839723287660822, 0.9842708356431279] 
 [0.0, 0.9077947669221139, 0.9460113312671069, 0.9603248839091876, 0.963084345061608, 0.9633060270877586, 0.9630347070627596, 0.9604215561306202, 0.960198250010326, 0.9609813535054028, 

In [ ]:
#####################################################################################
#
#####################################################################################
IxS_rho_graphing_df = IxS_Max_VNE_df[IxS_Max_VNE_df.gamma == 1]
IxS_rho_graphing_df = IxS_rho_graphing_df[IxS_rho_graphing_df.beta == 1]

IxI_rho_graphing_df = IxI_Max_VNE_df[IxI_Max_VNE_df.gamma == 1]
IxI_rho_graphing_df = IxI_rho_graphing_df[IxI_rho_graphing_df.beta == 1]

Homerange_IxI_rho_graphing_df = Homerange_IxI_Max_VNE_df[Homerange_IxI_Max_VNE_df.gamma == 1]
Homerange_IxI_rho_graphing_df = Homerange_IxI_rho_graphing_df[Homerange_IxI_rho_graphing_df.beta == 1]

Tripartite_rho_graphing_df = Tripartite_Max_VNE_df[Tripartite_Max_VNE_df.gamma == 1]
Tripartite_rho_graphing_df = Tripartite_rho_graphing_df[Tripartite_rho_graphing_df.beta == 1]

SxS_rho_graphing_df = SxS_Max_VNE_df[SxS_Max_VNE_df.gamma == 1]
SxS_rho_graphing_df = SxS_rho_graphing_df[SxS_rho_graphing_df.beta == 1]
#display(IxS_rho_graphing_df.shape)

In [ ]:
#####################################################################################
#
#####################################################################################
IxS_beta_graphing_df = IxS_Max_VNE_df[IxS_Max_VNE_df.gamma == 1]
IxS_beta_graphing_df = IxS_beta_graphing_df[IxS_beta_graphing_df.rho == 0.1]

IxI_beta_graphing_df = IxI_Max_VNE_df[IxI_Max_VNE_df.gamma == 1]
IxI_beta_graphing_df = IxI_beta_graphing_df[IxI_beta_graphing_df.rho == 0.1]

Homerange_IxI_beta_graphing_df = Homerange_IxI_Max_VNE_df[Homerange_IxI_Max_VNE_df.gamma == 1]
Homerange_IxI_beta_graphing_df = Homerange_IxI_beta_graphing_df[Homerange_IxI_beta_graphing_df.rho == 0.1]

Tripartite_beta_graphing_df = Tripartite_Max_VNE_df[Tripartite_Max_VNE_df.gamma == 1]
Tripartite_beta_graphing_df = Tripartite_beta_graphing_df[Tripartite_beta_graphing_df.rho == 0.1]

SxS_beta_graphing_df = SxS_Max_VNE_df[SxS_Max_VNE_df.gamma == 1]
SxS_beta_graphing_df = SxS_beta_graphing_df[SxS_beta_graphing_df.rho == 0.1]

#display(IxS_beta_graphing_df.shape)

In [ ]:
#####################################################################################
#
#####################################################################################
IxS_gamma_graphing_df = IxS_Max_VNE_df[IxS_Max_VNE_df.beta == 1]
IxS_gamma_graphing_df = IxS_gamma_graphing_df[IxS_gamma_graphing_df.rho == 0.1]

IxI_gamma_graphing_df = IxI_Max_VNE_df[IxI_Max_VNE_df.beta == 1]
IxI_gamma_graphing_df = IxI_gamma_graphing_df[IxI_gamma_graphing_df.rho == 0.1]

Homerange_IxI_gamma_graphing_df = Homerange_IxI_Max_VNE_df[Homerange_IxI_Max_VNE_df.beta == 1]
Homerange_IxI_gamma_graphing_df = Homerange_IxI_gamma_graphing_df[Homerange_IxI_gamma_graphing_df.rho == 0.1]

Tripartite_gamma_graphing_df = Tripartite_Max_VNE_df[Tripartite_Max_VNE_df.beta == 1]
Tripartite_gamma_graphing_df = Tripartite_gamma_graphing_df[Tripartite_gamma_graphing_df.rho == 0.1]

SxS_gamma_graphing_df = SxS_Max_VNE_df[SxS_Max_VNE_df.beta == 1]
SxS_gamma_graphing_df = SxS_gamma_graphing_df[SxS_gamma_graphing_df.rho == 0.1]

#display(IxS_gamma_graphing_df.shape)

In [ ]:
#####################################################################################
#
#####################################################################################
plt.figure()
#plt.subplot(221)
plt.grid(True)
plt.title('VNE Max for rho')
plt.xlabel('Rho Values')
plt.ylabel('Max VNE')
#plt.yticks(np.linspace(1.0, 1.5, 10, endpoint = True))
plt.legend(handles = [red_patch, green_patch, black_patch, blue_patch, yellow_patch], title='Projection')
plt.scatter(IxS_rho_graphing_df.rho.values, IxS_rho_graphing_df.MaxVNE.values, color = 'r')
plt.scatter(IxI_rho_graphing_df.rho.values, IxI_rho_graphing_df.MaxVNE.values, color = 'g')
plt.scatter(Homerange_IxI_rho_graphing_df.rho.values, Homerange_IxI_rho_graphing_df.MaxVNE.values, color = 'b')
plt.scatter(Tripartite_rho_graphing_df.rho.values, Tripartite_rho_graphing_df.MaxVNE.values, color = 'k')
plt.scatter(SxS_rho_graphing_df.rho.values, SxS_rho_graphing_df.MaxVNE.values, color = 'y')
plt.plot(IxS_rho_graphing_df.rho.values, IxS_rho_graphing_df.MaxVNE.values, color = 'r')
plt.plot(IxI_rho_graphing_df.rho.values, IxI_rho_graphing_df.MaxVNE.values, color = 'g')
plt.plot(Homerange_IxI_rho_graphing_df.rho.values, Homerange_IxI_rho_graphing_df.MaxVNE.values, color = 'b')
plt.plot(Tripartite_rho_graphing_df.rho.values, Tripartite_rho_graphing_df.MaxVNE.values, color = 'k')
plt.plot(SxS_rho_graphing_df.rho.values, SxS_rho_graphing_df.MaxVNE.values, color = 'y')
plt.show()

#plt.subplot(222)
plt.figure()
plt.grid(True)
plt.title('VNE Max for beta')
plt.xlabel('Beta Values')
plt.ylabel('Max VNE')
#plt.yticks(np.linspace(1.0, 1.5, 10, endpoint = True))
plt.legend(handles = [red_patch, green_patch, black_patch, blue_patch, yellow_patch], title='Projection')
plt.scatter(IxS_beta_graphing_df.beta.values, IxS_beta_graphing_df.MaxVNE.values, color = 'r')
plt.scatter(IxI_beta_graphing_df.beta.values, IxI_beta_graphing_df.MaxVNE.values, color = 'g')
plt.scatter(Homerange_IxI_beta_graphing_df.beta.values, Homerange_IxI_beta_graphing_df.MaxVNE.values, color = 'b')
plt.scatter(Tripartite_beta_graphing_df.beta.values, Tripartite_beta_graphing_df.MaxVNE.values, color = 'k')
plt.scatter(SxS_beta_graphing_df.beta.values, SxS_beta_graphing_df.MaxVNE.values, color = 'y')
plt.plot(IxS_beta_graphing_df.beta.values, IxS_beta_graphing_df.MaxVNE.values, color = 'r')
plt.plot(IxI_beta_graphing_df.beta.values, IxI_beta_graphing_df.MaxVNE.values, color = 'g')
plt.plot(Homerange_IxI_beta_graphing_df.beta.values, Homerange_IxI_beta_graphing_df.MaxVNE.values, color = 'b')
plt.plot(Tripartite_beta_graphing_df.beta.values, Tripartite_beta_graphing_df.MaxVNE.values, color = 'k')
plt.plot(SxS_beta_graphing_df.beta.values, SxS_beta_graphing_df.MaxVNE.values, color = 'y')
plt.show()

#plt.subplot(223)
plt.figure()
plt.grid(True)
plt.title('VNE Max for gamma')
plt.xlabel('Gamma Values')
plt.ylabel('Max VNE')
#plt.yticks(np.linspace(1.0, 1.5, 10, endpoint = True))
plt.legend(handles = [red_patch, green_patch, black_patch, blue_patch, yellow_patch], title='Projection')
plt.scatter(IxS_gamma_graphing_df.gamma.values, IxS_gamma_graphing_df.MaxVNE.values, color = 'r')
plt.scatter(IxI_gamma_graphing_df.gamma.values, IxI_gamma_graphing_df.MaxVNE.values, color = 'g')
plt.scatter(Homerange_IxI_gamma_graphing_df.gamma.values, Homerange_IxI_gamma_graphing_df.MaxVNE.values, color = 'b')
plt.scatter(Tripartite_gamma_graphing_df.gamma.values, Tripartite_gamma_graphing_df.MaxVNE.values, color = 'k')
plt.scatter(SxS_gamma_graphing_df.gamma.values, SxS_gamma_graphing_df.MaxVNE.values, color = 'y')
plt.plot(IxS_gamma_graphing_df.gamma.values, IxS_gamma_graphing_df.MaxVNE.values, color = 'r')
plt.plot(IxI_gamma_graphing_df.gamma.values, IxI_gamma_graphing_df.MaxVNE.values, color = 'g')
plt.plot(Homerange_IxI_gamma_graphing_df.gamma.values, Homerange_IxI_gamma_graphing_df.MaxVNE.values, color = 'b')
plt.plot(Tripartite_gamma_graphing_df.gamma.values, Tripartite_gamma_graphing_df.MaxVNE.values, color = 'k')
plt.plot(SxS_gamma_graphing_df.gamma.values, SxS_gamma_graphing_df.MaxVNE.values, color = 'y')
plt.show()

#print(SxS_gamma_graphing_df.gamma.values, SxS_gamma_graphing_df.MaxVNE.values)
#print(SxS_beta_graphing_df.beta.values, SxS_beta_graphing_df.MaxVNE.values)
#plt.subplot(224)
#plt.legend(handles = [red_patch, green_patch, black_patch, blue_patch, yellow_patch], title= 'Projection')
#plt.show()

#####################################################################################
#
#####################################################################################

#####################################################################################
#
#####################################################################################